spring:
  config:
    activate:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;MODE=MYSQL
    username: sa
    password:

  mail:
    host: smtp.gmail.com
    port: 465
    username: rmaprmap@gmail.com
    password: kyam tiuu dkrm mcqp
    auth: true
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
