spring:
  profiles:
    default: local

  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true


server:
  servlet:
    session:
      cookie:
        name: JSESSIONID
        domain: rmap.store
        http-only: true
        secure: true
        same-site: none
