spring:
  config:
    activate:
      on-profile: dev

  flyway:
    enabled: true
    baseline-on-migrate: false

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQLDialect

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DEV_DATASOURCE_URL}
    username: ${DEV_USERNAME}
    password: ${DEV_PASSWORD}

  mail:
    host: smtp.gmail.com
    port: 587
    username: rmaprmap2024@gmail.com
    password: ${SMTP_PASSWORD}
    auth: true
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
